python("print 'About to start importing MmmmTools  (this message is from userSetup.mel)'");python("print '(the T_Error msgs here can be safely ignored Maya/MmmmTools internals)'");
python("import pymel.all as pm");
python("import MmmmTools");
python("mmmmTools = MmmmTools.MmmmTools()");
python("print 'Done importing MmmmTools  (this message is from userSetup.mel)'");
python("print '\\n \\n \\n'");
//// MmmmTools shortcut to source GoZ//// Uncomment the next line to automatically source GoZ at startup//eval("source \"C:/Users/Public/Pixologic/GoZApps/Maya/GoZScript.mel\"");

